config/routes.rb
Rails.application.routes.draw do
  

  devise_for :users, controllers: {
  sessions:      'users/sessions',
  passwords:     'users/passwords',
  registrations: 'users/registrations'
}
  root 'home#top'

  resources :users, only: [:show, :index, :edit, :update ]

  resources :posts, only: [:show, :index, :new, :create, :destroy ]

  resource :relationships, only: [:create, :destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  attachment :profile_image

  has_many :active_relationships, class_name: "Relationship",
                                  foreign_key: "follower_id",
                                  dependent: :destroy
  has_many :passive_relationships, class_name: "Relationship",
                                   foreign_key: "followed_id",
                                   dependent: :destroy
  has_many :following, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships, source: :follower

  has_many :posts

  def follow(other_user)
    following << other_user
  end

  def unfollow(other_user)
    active_relationships.find_by(followed_id: other_user.id).destroy
  end

  def following?(other_user)
    following.include?(other_user)
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
  	@user = User.find(params[:id])
  end

  def index
  	@users = User.all
  end

  def edit
  	@user = User.find(params[:id])
  end

  def update
  	@user = User.find(params[:id])
  	if @user.update(user_params)

  	  redirect_to user_path(@user)

    else
      render 'edit'
    end
  end

  private
  def user_params
  	params.require(:user).permit(:name, :profile_image)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<%= form_for @user do |f| %>
  <%= f.text_field :name %><br>
  <%= f.attachment_field :profile_image %>
  <%= f.submit "OK" %>
<% end %>

app/views/users/index.html.erb

  <% @users.each do |user| %>
    <div class="row pt-2 pb-2">
      <div class="col-1">
        <%= attachment_image_tag user, :profile_image, :fill, 70, 70, class: "rounded-circle" %>
      </div>
      <div class="col-2">
    	<%= link_to user_path(user) do %>
    	  <%= user.name %>
    	<% end %>
      <%= @user.following.count %> following <%= @user.followers.count%> follower
      </div>
      <div class="col-9">
      	<% unless current_user == user %>
  	      <div class="btn btn-warning rounded-circle"><i class="fas fa-envelope text-white"></i></div>
          <% if current_user.following?(user) %>
            <%= link_to relationships_path(followed_id: user.id), method: :delete do %>
              <div class="btn btn-danger">unfollow</div>
            <% end %>
          <% else %>
            <%= link_to relationships_path(followed_id: user.id), method: :post do %>
              <div class="btn btn-outline-warning">follow</div>
            <% end %>
          <% end %>
        <% end %>
      </div>
    </div>
  <% end %>

app/views/users/show.html.erb
<div class="row" style="height: 50px;"></div>
<div class="row">
  <%= attachment_image_tag @user, :profile_image, :fill,100, 100, class: "rounded-circle"%>
</div>
<div class="row mb-5">
	<div class="col-3">
    <h3><%= @user.name %></h3>
  </div>
  <div class="col-5"></div>
  <div class="col-4">
  	<% unless current_user == @user %>
  	  <div class="btn btn-warning rounded-circle"><i class="fas fa-envelope text-white"></i></div>
      <% if current_user.following?(@user) %>
        <%= link_to relationships_path(followed_id: @user.id), method: :delete do %>
          <div class="btn btn-danger">unfollow</div>
        <% end %>
      <% else %>
        <%= link_to relationships_path(followed_id: @user.id), method: :post do %>
          <div class="btn btn-outline-warning">follow</div>
        <% end %>
      <% end %>
    <% end %>
    <% if @user == current_user %>
      <%= link_to edit_user_path(@user) do %>
        <div class="btn btn-warning">edit profile</div>
      <% end %>
    <% end %>
  </div>
</div>
<div class="row mb-5">
	<%= @user.following.count %> following <%= @user.followers.count%> follower
</div>
<div class="row">
  <div class="col-1"></div>
  <div class="col-11">
  	<% @user.posts.each do |post| %>
  	  <div class="border border-light">
        <div class="row">
      	  <div class="col-1">
      	  	<%= link_to user_path(post.user) do %>
      	      <%= attachment_image_tag post.user, :profile_image, :fill, 50, 50, class: "rounded-circle"%>
      	    <% end %>
      	  </div>
      	  <div class="col-11">
      	  	<div class="row" style="height: 20px;"></div>
      	    <p class="text-secondary">@<%= post.user.name %></p>
      	    <%= post.content %>
            <div><%= attachment_image_tag post, :content_image, :fill, 600, 400, class: "rounded mt-2 mb-2"%></div>
      	  </div>
        </div>
        <div class="row" style="height: 5px;"></div>
        <div class="row">
         	<div class="col-1"></div>
        	<div class="col-1">
        		<i class="fas fa-comment"></i>
        	</div>
        	<div class="col-7">
        		<i class="fas fa-heart"></i>
        	</div>
        	<div class="col-3">
        		<p><%= post.created_at %></p>
        	</div>
        </div>
        <div class="row">
          <div class="col-1"></div>
          <div class="col-11">
            <p>
              <a data-toggle="collapse" href="#collapseExample<%= post.id %>" role="button" aria-expanded="false" aria-controls="collapseExample<%= post.id %>">
                <i class="fas fa-map-marker-alt text-secondary"></i><span class="text-secondary">  <%= post.address %></span>
              </a>
            </p>
            <div class="collapse" id="collapseExample<%= post.id %>">
              <div class="card card-body">
                <script type="text/javascript">
                  function initMap(){
                   let map = new google.maps.Map(document.getElementById('map<%= post.id%>'), {
                   center: {lat: <%= post.latitude %>, lng: <%= post.longitude %>},
                   zoom: 15
                  });
                }
                </script>
                <style>
                  #map<%= post.id%> {
                    height: 500px;
                  }
                </style>
                <script src="https://maps.googleapis.com/maps/api/js?key=<%= ENV['API_KEY'] %>&callback=initMap" async defer></script>
                <div id="map<%= post.id%>"></div>
              </div>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>