config/routes.rb
Rails.application.routes.draw do
  

  devise_for :users, controllers: {
  sessions:      'users/sessions',
  passwords:     'users/passwords',
  registrations: 'users/registrations'
}
  root 'home#top'

  resources :users, only: [:show, :index, :edit, :update ]

  resources :posts, only: [:show, :index, :new, :create, :destroy ]

  resource :relationships, only: [:create, :destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_header.html.erb
<header class="bg-warning pb-2 pt-2">
	<div class="container">
    <div class="row">
    	<div class="col-4">
    	  <%= link_to root_path do %><h5 class="text-white"><i class="far fa-comments header-icon"></i> Chat app</h5><% end %>
      </div>
      <div class="col-4"></div>
 <!-- ---------------ログイン時--------------------- -->
      <div class="col-4">
  	  <% if user_signed_in? %>
        <%= link_to posts_path do %>
          <div class="btn btn-outline-light">Timeline</div>
        <% end %>
        <%= link_to user_path(current_user) do %>
          <div class="btn btn-outline-light">My page</div>
  	    <% end %>
  	    <%= link_to users_path do %>
          <div class="btn btn-outline-light">Users</div>
  	    <% end %>
  	    <%= link_to destroy_user_session_path, method: :delete  do %>
  	      <div class="btn btn-outline-light">Log out</div>
  	    <% end %>
<!-- ----------------------非ログイン時--------------- -->
      <% end %>
      </div>
    </div>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ChatApp2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script src="https://kit.fontawesome.com/f2ca94efa4.js" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header'%>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>